### ISSUE TITLE
Status update?

### ISSUE THREAD

**Issue by andrewgy8** [reinterpretcat/vrp#10]
I see VRP has been released with >1.0 a while ago. A belated congratulations 👏 

Does this mean the status of the project is no longer experimental like mentioned in the Readme? And if not, is there something that would make it more production ready?

**Comment by reinterpretcat** [comment]
I would say it is still experimental, but it has proven to be stable for some basic feature set. I'm aware about one production usage of the project (old version, CVRPTW variant).

Experimental status also allows me to move faster with breaking changes without commitment for API stability.

**Comment by andrewgy8** [comment]
It could be considered "production ready" but with no guarantee of non-breaking changes?

**Comment by reinterpretcat** [comment]
I would say yes, but some features are not tested well, e.g. time dependent VRP, interval break, etc.
