### ISSUE TITLE
Limit range/distance for electric vehicles

### ISSUE THREAD

**Issue by do-me** [reinterpretcat/vrp#102]
Hi all! 
I was skimming the docs and looking for the possibility to limit the range for E-vehicles. This is becoming increasingly important for real-life scenarios where particularly city centers can only be served by electric vehicles, so-called "low" and "ultra-low" emission zones. 
Charging is usually quite slow (at the moment) for delivery vehicles (above 2/3 tons) which reduces the optimization problem to just one route without charging breaks. However, for normal cars with fast charging it might be interesting as well to consider charging breaks of m minutes after each interval of k kilometers.

Is there any way to optimize such a problem in the current algorithm (e.g. by using some kind of cost matrix?) 
If not, are there any plans to include this kind of feature?

**Comment by reinterpretcat** [comment]
Hi, I'm alone here :)

Regarding limiting range/distance: there is already an optional hard constraint which can be used to limit total distance traveled by vehicle in the tour (check `maxDistance` here https://reinterpretcat.github.io/vrp/concepts/pragmatic/problem/vehicles.html).

 Regarding charging stations: with some relatively recent refactoring (~1 year old), it is possible to extend using similar to reload concept. But it would require some effort to implement (also there are multiple possibilities how the feature supposed to work).

**Comment by do-me** [comment]
It's just incredible what you put up all by yourself!

This is totally awesome! Excuse me for this unnecessary issue.
