### ISSUE TITLE
Something seems wrong with the pip package

### ISSUE THREAD

**Issue by blaggacao** [reinterpretcat/vrp#104]
```ipython
In [2]: import vrp_cli

In [3]: vrp_cli.lib
Out[3]: <Lib object for '/home/blaggacao/src/.../env/lib/python3.10/site-packages/vrp_cli/native.so'>

In [4]: vrp_cli.lib.solve_pragmatic
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File <ipython-input-4-e39910a693ad>:1
----> 1 vrp_cli.lib.solve_pragmatic

AttributeError: cffi library '/home/blaggacao/src/.../env/lib/python3.10/site-packages/vrp_cli/native.so' has no function, constant or global variable named 'solve_pragmatic'
```

I couldn't find the publishing routine in the repo automation so I assume publishing to pip is done manually from your local machine.

Maybe somehow something went wrong for this version, that I use:

```
  "vrp-cli~=1.21.0",
```

**Comment by blaggacao** [comment]
`v1.19.2` is good, btw:
```
In [2]: import vrp_cli

In [3]: vrp_cli.solve_pragmatic
Out[3]: <function vrp_cli.vrp_cli.solve_pragmatic(problem, matrices, config)>
```

**Comment by reinterpretcat** [comment]
Yeah, need to see what I did wrong with `maturin` and local Python environment. Or maybe it is better to spend some time and setup dedicated github actions. 

As workaround, you can try to build the package locally using `maturin` as described here: https://reinterpretcat.github.io/vrp/examples/interop/python.html#using-maturin

**Comment by blaggacao** [comment]
I got myself into an environment that _builds_ with `nix shell nixpkgs#cargo nixpkgs#rustc nixpkgs#maturin`. Let me see how far I can get from there.

**Comment by reinterpretcat** [comment]
I've added a dedicated github action [1] to build and publish to PyPI, but cannot make it work as it fails with `You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 43 MB`. Tried multiple times with reduced amount of architectures, cleaning deps, project's target folder.. No luck so far

[1] https://github.com/reinterpretcat/vrp/actions/workflows/maturin.yaml

**Comment by reinterpretcat** [comment]
I was able to publish update (1.21.1) to PyPI using dedicated github action, so it should work now on different OS families (windows, macos, linux) and architectures (x86_64, armv7), see https://github.com/reinterpretcat/vrp/blob/master/.github/workflows/maturin.yaml
