### ISSUE TITLE
Geojson in py_bindings

### ISSUE THREAD

**Issue by blaggacao** [reinterpretcat/vrp#106]
If this would hypothetically be an accepted feature...

Can you give me a couple of hints on how to implement and expose a conversion function from the `solution` returned by `vrp_cli.solve_pragmatic` to  GEOJson format?

I'd be happy to give it a try and implement something (and do a PR, ofc).

**Comment by reinterpretcat** [comment]
This should allow to get geojson output from py binding in next version after 1.21.1: https://github.com/reinterpretcat/vrp/commit/d4aa289c7fb637ffe1f17c48f393ee2a572e09a4
