### ISSUE TITLE
Differences in Pragmatic format for cli / javascript

### ISSUE THREAD

**Issue by pierrethiriet** [reinterpretcat/vrp#11]
Thanks a lot for the developpement of the very useful vrp-cli. 
I am building a small web app for optimizing local food products. Your documentation is very nice, but I did struggle to figure out that the _pragmatic format_ is not the same between the **cli interface** and when using **through JavaScript** :
For example: 
for CLI usage:
```
    "jobs": [
      {
        "id": "job1",
        "deliveries": [
          {
            "places": [
              { ...
```
For JavaScript (places.delivery instead of deliveries.places ):
```
    "jobs": [
      {
        "id": "job",
        "places": {
          "delivery": {
            "location": {
```
Or  
for CLI usage:
```
        "shifts": [{
            "start": {
              "earliest": "2019-07-04T09:00:00Z",
              "location": {
```
For JavaScript (_time_ instead of _earliest_ ):
```
        "shifts": [{
          "start": {
            "time": "2020-04-07T00:00:00Z",
```
Therefore, it is not possible to produce a pragmatic problem usable for both interface which could be useful at some point.

A side comment, I am really struggling to import vrp-cli (generated through wasm-pack) in JavaScript (NodeJs/Express, bundle with parcel). For a strange and unknown reason it did work on a project, but fails in any new projects. Did you have any experience or tips on that matter?

**Comment by reinterpretcat** [comment]
Hi,

this example demonstrates convertion from undocumented `hre` format to `pragmatic`. In short, `hre` is similar to `pragmatic` format, but incompatible with it. Actually, I will delete `hre` at some point as the main purpose of it is to simplify promotion of the library in the project I'm working on.

So, I updated example in the docs to avoid confusion and double checked that it is working with `web` target: 
https://reinterpretcat.github.io/vrp/examples/interop/javascript.html

Regarding nodejs, I haven't tested it, to be honest. Have you build it using `nodejs` target as described here: https://rustwasm.github.io/wasm-pack/book/commands/build.html#target ?

**Comment by pierrethiriet** [comment]
Thanks a lot for your help and thanks for updating the example.

I moved all in true _pragmatic_ format and it is working perfectly.

Regarding _JavaScript_, I am still struggling, but, with an ugly trick it is working.

**Comment by reinterpretcat** [comment]
If you run it with nodejs on backend, I would suggest to look into building native library and use it from nodejs via native bindings. wasm built is single threaded, so it is much slower than native version.

**Comment by pierrethiriet** [comment]
Sorry for the late reply.
I am still checking if I'll move for _client_ or _server_ side implementation. But I surely try to use native bindings if I'll go for NodeJS.
