### ISSUE TITLE
Return current best solution on SIGTERM

### ISSUE THREAD

**Issue by qwelias** [reinterpretcat/vrp#119]
I haven't looked at the source yet, but from the current CLI behaviour `max-time` option interrupts solution search and returns the current best.
Would it be possible to do the same upon receiving SIGTERM (or another signal in case of any conflicts)?

**Comment by reinterpretcat** [comment]
Yes, it is possible. At the moment, the search is also interrupted by ctrl+C combination when vrp-cli is used

**Comment by qwelias** [comment]
Nice, SIGINT works!
