### ISSUE TITLE
Location of unassigned jobs in solution

### ISSUE THREAD

**Issue by pierrethiriet** [reinterpretcat/vrp#12]
It is more a comment that an issue.
I am building _Geojson_ directly in _JavaScript_ as it seems that the _vrp-cli_ do not export _GeoJson_ in this configuration. 
I did add the _unassigned jobs_ to the _GeoJson_ and to build the map (grey circles in the map below) as it is an important information to get in the planning process (at least in our case).
![image](https://user-images.githubusercontent.com/33446598/101030446-9ca05400-3579-11eb-8e71-1ab92899cde3.png)
The only issue here is that in the solution object (solution.json), the location of the _unassigned jobs_ are not provided, contrary to the served one. It requires then to join the solution with the raw data. It is not a big issue, but I wonder if there is a specific reason not returning this information in the solution object.
Thanks a lot.

**Comment by reinterpretcat** [comment]
The main reason is that a single job definition can have multiple locations, e.g.
* job with multiple location variants (use case is `deliver in the morning to my work or in the evening to my home`)
* job with multiple pickups and deliveries (the simplest is pickup and delivery use case)

So, solution would have to replicate all these locations somehow which would be probably close to original job definition. I think it is better to simply keep a "jobId" reference in the solution

**Comment by pierrethiriet** [comment]
Thanks, it is quite clear now.
Obviously, my use case is quite simple in regard to the wide range of possibilities that vrp-cli offers. In that perspective I understand that my question doesn’t make sense.
Thanks again.
