### ISSUE TITLE
VRP does not respond, ignores SIGINT and max-time

### ISSUE THREAD

**Issue by ilibar-zpt** [reinterpretcat/vrp#137]
The execution hangs and does not respond to `SIGINT` (was sent in 5min), had to `SIGKILL` after another 5 minutes.

Version: 1.22.1

Command:
```sh
vrp-cli solve pragmatic problem.json --matrix car.matrix.json --out-result result.json --log --max-time 300 --min-cv sample,10000,0.05,true --parallelism 1,1
```
[Files and stdout](https://gist.github.com/ilibar-zpt/39c894145a3d7c1893bc631af6de90d6)
Also tried with `--parallelism 2,2`, still hangs.

Kernel: `Linux 6.5.9-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 26 Oct 2023 00:52:20 +0000`
CPU: `AMD Ryzen 7 PRO 6850U with Radeon Graphics`

**Comment by reinterpretcat** [comment]
Hi,

I tested locally and cannot reproduce the issue (sent SIGINT shortly after run). Everything works as expected.

Btw, what is motivation behind parallelism settings reconfiguration with single thread pool and single thread?

**Comment by ilibar-zpt** [comment]
Seems like there was a race condition on my side, current guess is I was running vrp too soon after compiling the problem. Sorry for bothering.

> Btw, what is motivation behind parallelism settings reconfiguration with single thread pool and single thread?

I was doing some testing a while ago on smaller datasets, it seemed like `parallelism 1,1` was converging faster than anything else, I'll try to file an issue on that if you're curious, but cannot promise it atm

**Comment by ilibar-zpt** [comment]
@reinterpretcat  FYI I think figured what was happening.

This reproduces only in a docker container, for some reason performance inside docker is severely capped, tho they [claim](https://docs.docker.com/config/containers/resource_constraints/#cpu) it's not capped.

Running in `rust:1.70-alpine` is much slower than in `rust:1.70-buster`, and if process is interrupted before we got `created initial solution` it will hang for a while

**Comment by ilibar-zpt** [comment]
Just noticed your comment on musl/glibc in README, I think it runs times faster with glibc on my machine, could be different on the server tho

**Comment by reinterpretcat** [comment]
General idea of existing docker image is just to give ability to play with the solver quickly with small problems. For real world tasks, I would recommend to build image with all native CPU optimizations on hardware where it is supposed to be run
