### ISSUE TITLE
Space in path on Win creates an error

### ISSUE THREAD

**Issue by xeroxstar** [reinterpretcat/vrp#14]
Hello,
I am running vrp-cli and when i am trying to execute a command that contains a space in the path
`vrp-cli solve pragmatic "C:/my projects/vrp-cli/problem.json" -o "C:/my projects/vrp-cli/solution.json" --log`
I am getting an error:

```
error: Found argument 'projects/vrp-cli/problem.json"' which wasn't expected, or isn't vali
d in this context

USAGE:
    vrp-cli solve [FLAGS] [OPTIONS] <FORMAT> <PROBLEM>

For more information try --help
```
I tried to google it but i didn't find anything helpful, is there a fix to it?
Thank you

**Comment by reinterpretcat** [comment]
Just checked path with space on Linux: it seems to work. 

I'm using `clap` library to build CLI and seems doesn't have such issue reported. I would need to investigate, but I don't have Windows. I would suggest just to avoid spaces in path at the moment.

**Comment by xeroxstar** [comment]
I end up using VirtualBox and installing ubuntu ISO to make it work, by the way, great work, the installation and setup were smooth though i am not familiar with rust but i had not problem to setup everything and docs are great !!!

**Comment by reinterpretcat** [comment]
Thanks for feedback!

If you have docker installed, you can also try to use an image from github container registry, see latest version and instructions here: https://github.com/users/reinterpretcat/packages/container/package/vrp%2Fvrp-cli
