### ISSUE TITLE
Routing matrix format?

### ISSUE THREAD

**Issue by xeroxstar** [reinterpretcat/vrp#15]
Hello again,
I have a problem with Routing matrix format? I am using osrm database, once i fetch the distance matrix i am getting:
```
durations: [
    [ 0, 558.2, 2449, 836.9 ],
    [ 576.5, 0, 2794.3, 1188.9 ],
    [ 2504.2, 2761.7, 0, 2096.3 ],
    [ 859.6, 1098.7, 2028.4, 0 ]
]
```
but in docs it's says I need the travelTimes and the distances:
```
{
  "profile": "normal_car",
  "travelTimes": [
    0,
    609,
    981,
    906,
    813,
    0,
    371,
    590,
    1055,
    514,
    0,
    439,
    948,
    511,
    463,
    0
  ],
  "distances": [
    0,
    3840,
    5994,
    5333,
    4696,
    0,
    2154,
    3226,
    5763,
    2674,
    0,
    2145,
    5112,
    2470,
    2152,
    0
  ]
}
```

How do i get kind of matrix? I have durations( i assume it's travelTimes) but i don't have distances, the only distances i can get is from osrm database:
```
 {
  code: 'Ok',
  routes: [
    {
      geometry: 'qcjuGhl{_Me]yMh]erAilDqvAygDqd@mCr[{SaFjA~V}~@bIqgCu|@icCcG_dAutAbIhN_d@`dAteBbqKycA~nQlRxaD~mEjtKlgBpg@fcBvmE~aAdr@rvAheBpSbdBwIlk@epJrbPc\\la@c\\{W{e@|}@ze@
}}@`j@hVruO_kXd|Aeh@pgAahD@igB~h@ee@yjAgeBms@qjC{y@ckAsaBevEsrEgtClPwn@juEcnFlp@_qC|cAuqCum@}V',
      legs: [Array],
      distance: 108110.8,
      duration: 5858.9,
      weight_name: 'routability',
      weight: 5858.9
    }
  ],
  waypoints: [
    {
      hint: 'F8EBgP___38fAAAAPwAAAAAAAAAAAAAA_k4KQhvXDEIAAAAAAAAAAB8AAAA_AAAAAAAAAAAAAAC5AwAArMed-93etwLmx537jd-3AgAAvxF-_wId',
      distance: 20.077371,
      name: 'Boulevard Joseph-Renaud',
      location: [Array]
    },
    {
      hint: 'elgUgJtYFIAiAAAADAAAAA4AAAAAAAAABui8QVPMA0F09x5BAAAAACIAAAAMAAAADgAAAAAAAAC5AwAAIFOe-5m0uALjUp77KrS4AgEALxJ-_wId',
      distance: 13.22092,
      name: 'Rue Charles Goulet',
      location: [Array]
    },
    {
      hint: 'ptMIgBTUCIAkAAAAOAAAADICAAAAAAAA-WHLQctDGUIBc8NDAAAAACQAAAA4AAAAMgIAAAAAAAC5AwAAQ7OX--touQJDspf7b2m5AgcATwJ-_wId',
      distance: 24.747056,
      name: 'Rue du Noroît',
      location: [Array]
    },
    {
      hint: 'F8EBgP___38fAAAAPwAAAAAAAAAAAAAA_k4KQhvXDEIAAAAAAAAAAB8AAAA_AAAAAAAAAAAAAAC5AwAArMed-93etwLmx537jd-3AgAAvxF-_wId',
      distance: 20.077371,
      name: 'Boulevard Joseph-Renaud',
      location: [Array]
    }
  ]
}
```

So how do i get the matrix as described in docs https://reinterpretcat.github.io/vrp/concepts/pragmatic/routing/format.html
Thanks

**Comment by reinterpretcat** [comment]
The simplest approach would be to find api which returns both, duration and distance, matrices at the same response. Otherwise you would need to have some preprocessing steps to create expected json. 

For osrm, I've quickly searched and found the following two requests examples from [1]:

```
curl 'http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?annotations=duration'

curl 'http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?annotations=distance'

```

It seems you can also get distances/durations at the same request too:

```
curl 'http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?annotations=distance,duration'
```

The response I got:

```                                                                                                                                     
{                                                                                                                                                                                                                         
  "code": "Ok",                                                                                                                                                                                                           
  "distances": [                                                                                                                                                                                                          
    [                                                                                                                                                                                                                     
      0,                                                                                                                                                                                                                  
      1887.4,                                                                                                                                                                                                             
      3803                                                                                                                                                                                                                
    ],                                                                                                                                                                                                                    
    [                                                                                                                                                                                                                     
      1903.1,                                                                                                                                                                                                             
      0,                                                                                                                                                                                                                  
      2845.8                                                                                                                                                                                                              
    ],                                                                                                                                                                                                                    
    [                                                                                                                                                                                                                     
      4002.9,                                                                                                                                                                                                             
      3015.3,                                                                                                                                                                                                             
      0                                                                                                                                                                                                                   
    ]                                                                                                                                                                                                                     
  ],                                                                                                                                                                                                                      
  "durations": [                                                                                                                                                                                                          
    [                                                                                                                                                                                                                     
      0,                                                                                                                                                                                                                  
      251.5,                                                                                                                                                                                                              
      384.5                                                                                                                                                                                                               
    ],                                                                                                                                                                                                                    
    [                                                                                                                                                                                                                     
      258.2,                                                                                                                                                                                                              
      0,                                                                                                                                                                                                                  
      363.5                                                                                                                                                                                                               
    ],                                                                                                                                                                                                                    
    [                                                                                                                                                                                                                     
      458.2,                                                                                                                                                                                                              
      413.4,                                                                                                                                                                                                              
      0                                                                                                                                                                                                                   
    ]                                                                                                                                                                                                                     
  ],                                                                                                                                                                                                                      
  "sources": [                                                                                                                                                                                                            
    {                                                                                                                                                                                                                     
      "hint": "M6zQgf7RvpIYAAAAJgAAAAAAAAAAAAAASjFaQU1xpUEAAAAAAAAAAAwAAAATAAAAAAAAAAAAAADsFgEA_kvMAKlYIQM8TMwArVghAwAA7woZ5eP6",
      "distance": 4.231666,
      "location": [
        13.388798,
        52.517033
      ],
      "name": "Friedrichstraße"
    },
...
```

You don't have to rename `durations` to `travelTimes`: both names are supported, but you would need to unwrap matrices from 2d to 1d array. Also please check whether you need to transpose matrices or not.

[1] https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md

**Comment by xeroxstar** [comment]
> The simplest approach would be to find api which returns both, duration and distance, matrices at the same response. Otherwise you would need to have some preprocessing steps to create expected json.
> 
> For osrm, I've quickly searched and found the following two requests examples from [1]:
> 
> ```
> curl 'http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?annotations=duration'
> 
> curl 'http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?annotations=distance'
> ```
> 
> It seems you can also get distances/durations at the same request too:
> 
> ```
> curl 'http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?annotations=distance,duration'
> ```
> 
> The response I got:
> 
> ```
> {                                                                                                                                                                                                                         
>   "code": "Ok",                                                                                                                                                                                                           
>   "distances": [                                                                                                                                                                                                          
>     [                                                                                                                                                                                                                     
>       0,                                                                                                                                                                                                                  
>       1887.4,                                                                                                                                                                                                             
>       3803                                                                                                                                                                                                                
>     ],                                                                                                                                                                                                                    
>     [                                                                                                                                                                                                                     
>       1903.1,                                                                                                                                                                                                             
>       0,                                                                                                                                                                                                                  
>       2845.8                                                                                                                                                                                                              
>     ],                                                                                                                                                                                                                    
>     [                                                                                                                                                                                                                     
>       4002.9,                                                                                                                                                                                                             
>       3015.3,                                                                                                                                                                                                             
>       0                                                                                                                                                                                                                   
>     ]                                                                                                                                                                                                                     
>   ],                                                                                                                                                                                                                      
>   "durations": [                                                                                                                                                                                                          
>     [                                                                                                                                                                                                                     
>       0,                                                                                                                                                                                                                  
>       251.5,                                                                                                                                                                                                              
>       384.5                                                                                                                                                                                                               
>     ],                                                                                                                                                                                                                    
>     [                                                                                                                                                                                                                     
>       258.2,                                                                                                                                                                                                              
>       0,                                                                                                                                                                                                                  
>       363.5                                                                                                                                                                                                               
>     ],                                                                                                                                                                                                                    
>     [                                                                                                                                                                                                                     
>       458.2,                                                                                                                                                                                                              
>       413.4,                                                                                                                                                                                                              
>       0                                                                                                                                                                                                                   
>     ]                                                                                                                                                                                                                     
>   ],                                                                                                                                                                                                                      
>   "sources": [                                                                                                                                                                                                            
>     {                                                                                                                                                                                                                     
>       "hint": "M6zQgf7RvpIYAAAAJgAAAAAAAAAAAAAASjFaQU1xpUEAAAAAAAAAAAwAAAATAAAAAAAAAAAAAADsFgEA_kvMAKlYIQM8TMwArVghAwAA7woZ5eP6",
>       "distance": 4.231666,
>       "location": [
>         13.388798,
>         52.517033
>       ],
>       "name": "Friedrichstraße"
>     },
> ...
> ```
> 
> You don't have to rename `durations` to `travelTimes`: both names are supported, but you would need to unwrap matrices from 2d to 1d array. Also please check whether you need to transpose matrices or not.
> 
> [1] https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md

This is great, thank you!!!

**Comment by xeroxstar** [comment]
Sorry to bother you again, vrp-cli gives me an error :`'amount of locations does not match matrix dimension', action: 'check matrix size: max location index '21' + 1 should be equal to matrix size ('21')';`

I am getting the same response as you from osrm, if you look at the **distances array**
```
"distances": [                                                                                                                                                                                                          
    [                                                                                                                                                                                                                     
      0,                                                                                                                                                                                                                  
      1887.4,                                                                                                                                                                                                             
      3803                                                                                                                                                                                                                
    ],                                                                                                                                                                                                                    
    [                                                                                                                                                                                                                     
      1903.1,                                                                                                                                                                                                             
      0,                                                                                                                                                                                                                  
      2845.8                                                                                                                                                                                                              
    ],                                                                                                                                                                                                                    
    [                                                                                                                                                                                                                     
      4002.9,                                                                                                                                                                                                             
      3015.3,                                                                                                                                                                                                             
      0                                                                                                                                                                                                                   
    ]                                                                                                                                                                                                                     
  ]
```
 which are in 2D array and if I convert them into 1D array, I am getting a new array length of 9

`[0, 1887.4, 3803, 1903.1, 0, 2845.8, 4002.9, 3015.3, 0]`

 which I think is wrong because I need a matrix array length of 3 values and not 9, I really got confused at this point and not sure how others solved it.

**Comment by xeroxstar** [comment]
Nevermind, i looked at this example https://reinterpretcat.github.io/vrp/examples/interop/javascript.html and figured out where the problems and it's WORKING now !!!! 

Sorry to bother you with that and i hope this discussion will help to others!!!
