### ISSUE TITLE
Unexpected Output Format in Li & Lim Benchmark Solution

### ISSUE THREAD

**Issue by Emil-Hietanen** [reinterpretcat/vrp#158]
I ran the Li & Lim benchmarks and got the following solution for `lcl101.txt`:

```
Route 1: mlt37 mlt35 mlt33 mlt32 mlt33 mlt35 ...
Route 2: mlt10 mlt10 mlt12 mlt12 mlt14 mlt15 ...
...
Cost: 828.94

```

However, the expected format (based on the highest score recorded) looks like this:

```
Route 1: 81 78 104 76 71 ...
Route 2: 57 55 54 53 56 ...
...

```

Is the difference in node labeling (e.g., mltXX vs. XX) intentional, or am I missing something in the configuration that leads to this discrepancy?

Thanks in advance for your help!

**Comment by reinterpretcat** [comment]
I would say it should be in expected format. I'll investigate

**Comment by reinterpretcat** [comment]
Removed prefix in https://github.com/reinterpretcat/vrp/commit/b18a8580af3c55d39c2a18126c13c00941a5f8b9

**Comment by Emil-Hietanen** [comment]
Thanks for investigating the issue!

I've noticed that the task IDs in the solution are not unique. For instance, the generated test in the test includes duplicate IDs, as shown below:

```
vec!["1", "0", "1", "3", "3", "5", "4", "2", "4", "2", "5", "0"],
vec!["10", "10", "12", "12", "14", "15", "13", "14", "11", "11", "13", "15"],
vec!["16", "17", "16", "18", "17", "20", "18", "19", "19", "20"],
vec!["22", "21", "22", "21", "23", "23", "24", "24", "27", "27", "26", "26", "25", "25"],
vec!["31", "31", "29", "28", "30", "28", "29", "30"],
vec!["37", "35", "33", "32", "33", "35", "37", "34", "34", "32", "36", "36"],
vec!["42", "40", "40", "39", "38", "42", "39", "38", "41", "41"],
vec!["47", "46", "45", "46", "43", "44", "43", "47", "44", "45"],
vec!["51", "49", "51", "49", "48", "48", "50", "50", "52", "52"],
vec!["6", "6", "8", "9", "9", "7", "7", "8"]
```

Could you help ensure that each task ID is unique?

**Comment by reinterpretcat** [comment]
Originally, it is about pickup and delivery jobs: each job consists from pickup part and the corresponding delivery part. That's why each id is in the solution present twice: first for pickup place and then second for delivery. 

However, I've started to check documentation about this LiLim benchmark data and got a bit confused: best know solutions doesn't have duplicated ids! Seems my implementation is not correct here..
