### ISSUE TITLE
Jobs with many deliveries => Initial Solution is never finished

### ISSUE THREAD

**Issue by K-Leon** [reinterpretcat/vrp#18]
**First: You're doing an awesome job!**

While playing around i noticed a strange behavior: 
I tried to group Stops together (whatever Vehicle takes them - they should be delivered together). At a certain point ( a few jobs had as much as 11 or 12 deliveries ) the solver took forever for an initial solution. 

It is stuck at 100% CPU (Just one Core) with the preparation task. This means nothing happened after Log entry "problem has a total of n jobs..."

Running this task without grouped deliveries works like a charm.

Do you have any idea what is going on and if there may be a simple workaround?

**Comment by reinterpretcat** [comment]
Thanks for feedback!

11 deliveries in one job means 11! permutations to consider. I limit at each insertion attempt amount of considered permutations with hardcoded `const MULTI_JOB_SAMPLE_SIZE: usize = 3;`, but maybe there is some issue in the logic. I'll check on weekend. Do you have a sample data to reproduce?

**Comment by K-Leon** [comment]
I'll clean up and anonymize the data asap - is there a mail or sth. where i can send you a gist?

( dropping time constraints isn't helping either sadly )

**Comment by reinterpretcat** [comment]
yes, you can send it to ilya.builuk at gmail com
also you can use location as index instead of real coordinates (this require a routing matrix to be supplied)

**Comment by reinterpretcat** [comment]
Can confirm: the bug is in logic which generates permutation indices for job with multiple sub-jobs (e.g. deliveries). It is not able to handle a large amount of permutations (e.g. 11!). So, I need to revise approach a bit.
