### ISSUE TITLE
Javascript termination criteria – maxGeneration

### ISSUE THREAD

**Issue by pierrethiriet** [reinterpretcat/vrp#19]
In JavaScript, when I am passing a config object such as the following, the solver work perfectly :
```
  const config = {
      "termination": {
          "maxTime": 120,
          "maxGenerations": 1000
      }
  };
``` 
But, following your advice in a previous discussion:

> I would recommend setting only a time limit with --max-time  

I then wanted to remove the `maxGenerations` criteria.
But when passing the config object with only `maxTime` criteria:
``` 
  const config = {
      "termination": {
          "maxTime": 120,
      }
  };
``` 
The solver *never stops running* and the CPU seems to keep working. This issue appears on the current version of vrp-cli, *v1.8.0*.
Is it a normal behavior and a default value should always be given?
Thanks a lot.

**Comment by reinterpretcat** [comment]
No, this is not proper behavior. I will check it

**Comment by reinterpretcat** [comment]
Hm, cannot reproduce it with 10 secs and 120 secs using example problem from here: https://reinterpretcat.github.io/vrp/examples/interop/javascript.html

**Comment by pierrethiriet** [comment]
Sorry, it is all my fault.
I didn't realized that `maxGenerations` was actually the current limitating factor. So the actual behavior is infact perfectlly good. The process end up well after the maximum time selected.
So I may end up by setting a converging criteria with `cost-variation`.
Thanks a lot.
