### ISSUE TITLE
Driver shift and capacity question

### ISSUE THREAD

**Issue by xeroxstar** [reinterpretcat/vrp#23]
Hello,
I have a question, how to balance capacity with the driver time shift? In my case we have two drivers with total of 20 jobs, one driver starts his shift at 8:00 and ends at 10:00, the other driver starts from 8:00 and ends his shift at 17:00 (full working day).  In most cases all drivers have a full day shift (from 8:00 to 17:00) and in this case i can calculate capacity for each driver( we divide total jobs with total amount of drivers, for example 20 jobs/2 drivers= 10 jobs each ) but, sometimes we have drivers who can do only half day or few hours shift, so in this case we can't divide total jobs between two drivers because the driver that has shift of few hours the total capacity is unknown for me. In this case we need that driver that has few hours a day will get jobs for few hours and the rest jobs will be assigned to other drivers base on time shift.

So here is how we solve the capacities between the two drivers for 20 jobs with same time shift:
Driver 1 capacity: jobs.length/drivers.length = 10 - shift = 8:00-17:00
Driver 2 capacity: jobs.length/drivers.length = 10 - shift = 8:00-17:00

Here is a how we are trying to solve the problem with two drivers but with different time shift:
Driver 1 capacity: jobs.length/drivers.length = 10 - shift = 8:00-17:00
Driver 2 capacity: jobs.length/drivers.length = 10 - shift = 8:00-10:00

![image](https://user-images.githubusercontent.com/6754584/110001475-6db58d80-7ce2-11eb-94d0-993188b7d1c6.png)

As you can see the red driver (Driver 1) gets his 10 jobs and the driver in green (Driver 2)  gets 3 jobs but there is 7 unsigned jobs that need to be assigned to Driver 1 (red). 

Thank you

**Comment by reinterpretcat** [comment]
Hi,

I'm not sure that I got your use case. For me, it seems like you want to limit amount of jobs assigned to each vehicle rather than balancing. Have you tried to use `tourSize` limit on vehicle type: `tourSize (optional): max amount of activities in the tour (without departure/arrival)` ?

**Comment by xeroxstar** [comment]
> Hi,
> 
> I'm not sure that I got your use case. For me, it seems like you want to limit amount of jobs assigned to each vehicle rather than balancing. Have you tried to use `tourSize` limit on vehicle type: `tourSize (optional): max amount of activities in the tour (without departure/arrival)` ?

I want that all 20 jobs will be assigned between 2 drivers but the driver #1 can work only from 8:00 to 10:00 so he should get the amount of jobs he can achieve in 2 hours, so in my case the driver #1 should get less jobs rather the another driver because for the another driver the time shift is from 8:00 to 17:00. On the screenshot you can see that driver in green gets 3 jobs but driver in red gets only 10 jobs but he need to have 17 jobs.  I am not sure about  `tourSize` i cant find anything in docs about it, can you provide a link please?

Thx

**Comment by reinterpretcat** [comment]
What's about to define two vehicle types with different shift times, but with enough capacity? Shift time is a hard constraint and the solve has to assign jobs without its violation.

Vehicle type definition is described here: https://reinterpretcat.github.io/vrp/concepts/pragmatic/problem/vehicles.html

**Comment by xeroxstar** [comment]
> What's about to define two vehicle types with different shift times, but with enough capacity? Shift time is a hard constraint and the solve has to assign jobs without its violation.
> 
> Vehicle type definition is described here: https://reinterpretcat.github.io/vrp/concepts/pragmatic/problem/vehicles.html

Thx for the link and the tip, let me go through the docs again i will be back with you if i will not able to solve it.
