### ISSUE TITLE
Possibility to define a vehicle speed factor

### ISSUE THREAD

**Issue by leobudima** [reinterpretcat/vrp#27]
Hi - first of all, huge compliments on what seems to be an amazing and all-encompassing project - I was delighted when I saw all the features you are covering and can't wait to interface with it and give it a go with our use-cases!

There is just one thing that I would be missing at this moment - ability to specify a speed factor for a vehicle (whether this vehicle is quicker or slower than distance matrix travel times), which is of very high value when dealing with different levels of experience / performance in drivers - some are more experienced or just generally faster than the baseline, and some are slower. In case of dense deliveries (e.g. food) with narrow time-windows, it can make a lot of difference.  

I was curious if there was something in the project that can potentially be used as a workaround for this use-case?

Thank you very much!

**Comment by reinterpretcat** [comment]
Hi,
thanks for feedback.

Regarding to a vehicle speed factor: I would say this can be modeled using different routing profiles with different matrices. See this example: https://reinterpretcat.github.io/vrp/examples/pragmatic/basics/profiles.html
So, you would need to prepare multiple matrices and use them accordingly, e.g. set to each vehicle the proper one and specify matrix paths using `-m` option in the order of profiles definition in the problem

**Comment by andrewgy8** [comment]
I agree with what @reinterpretcat says. The speed of a vehicle is typically defined by the matrix generator and the profile used for for traversing the map. 

You can see a bunch of provided profiles by OpenRouteService's api [here](https://openrouteservice.org/dev/#/api-docs/matrix/get). Just click on the profiles dropdown. 

And here is a short list too. 
<img width="431" alt="Screen Shot 2021-03-31 at 3 07 29 PM" src="https://user-images.githubusercontent.com/14836934/113149223-10562300-9233-11eb-8baa-abcaa27e28d0.png">

**Comment by leobudima** [comment]
Thanks to both for your replies! I agree that the best way to do it for a certain type / group of vehicles is through using different matrix profiles - and vrp nicely supports providing multiple matrices as input, which is amazing. In the end, you can even apply a scaling factor to travel times in already calculated matrices and manage types / groups of vehicles that way. 

This feature allows adjusting those values further on individual driver level - e.g. this driver in practice takes on average 20% more time than baseline, this one is faster and needs 10% less time etc...Basically, when calculating for this vehicle, instead of using the value directly from the matrix, the factor gets applied to it first. 

To re-iterate, just hoping to give additional information if you guys consider it useful, the feature set you have is quite rich and broad already! :)

Based on our customers' experiences, this is crucial for them to take into account when time-windows are very tight and deliveries dense (e.g. food delivery). It exists as an input in multiple commercial solutions (e.g. Maxoptra, WorkWave...), is being added to VROOM library etc...

**Comment by leobudima** [comment]
Great, happy that it sounds useful! 

In most cases where I've seen it, yes, it only gets applied to travel time, and that is probably least complicated implementation-wise. For use-cases like delivery (vs e.g. servicing equipment), travel times are probably a much bigger component of total job time and much more depend on driver "performance", than service time, which is also small comparatively.

**Comment by reinterpretcat** [comment]
Working on it in a branch: https://github.com/reinterpretcat/vrp/commit/4ccf7ff748b2e4855d42a0c98b39965477fbb660

only missing some tests so far

**Comment by reinterpretcat** [comment]
I've refactored a bit a pragmatic format to have the setting consistent: it is part of vehicle profile via `fleet.vehicles.profile scale` property (available in master). Ideally, it should be moved to `fleet.drivers`, but drivers-vehicles match feature is not yet landed.

**Comment by reinterpretcat** [comment]
Released in 1.10.0

**Comment by leobudima** [comment]
Amazing, thank you very much for your support and very quick response!
