### ISSUE TITLE
A name?

### ISSUE THREAD

**Issue by Trollgeir** [reinterpretcat/vrp#3]
Is there any plans of giving this library a name other than `vrp`? Making benchmarks for several VRP-solvers made this a challenge.

**Comment by reinterpretcat** [comment]
Good point! I was not able to come up with a good name, need to give it priority.

**Comment by unguul** [comment]
We all know there's only 2 things which are difficult to do: https://martinfowler.com/bliki/TwoHardThings.html

**Comment by reinterpretcat** [comment]
I would stick to `vrp-cli` at the moment :)
