### ISSUE TITLE
Предложения по Dispatch и Reload

### ISSUE THREAD

**Issue by yuranov** [reinterpretcat/vrp#32]
Илья, доброго времени суток!

У меня есть предложение относительно сущностей Dispatch и Reload.
По условиям местоположение Dispatch быть уникальным, но есть предложение снять уникальность, т.к., например, транспорт может находиться на стоянке у склада в самом начале маршрута. 
Также есть предложение распространить ограничения Dispatch на Reload и наоборот т.к. они с большой вероятностью могут быть одним и тем же местом. Т.е. в начале маршрута необходимо учитывать время на погрузку, а при перезагрузке необходимо учитывать ограничения одновременных загрузок. Или в таком случае может быть стоит выделить отдельную сущность как "Cклад", которая будет сочетать свойства Dispatch и Reload?

**Comment by reinterpretcat** [comment]
Добрый день!

В принципе, идея  Dispatch - это моделирование склада (Warehouse). Вначале, машина может находится где угодно, например, в личном гараже водителя, а затем она едет на склад за посылками (jobs).  У склада есть ограниченная пропускная способность: он может пропустить через себя лишь определенное число машин. Ограничение по местоположению тут, в принципе, мне кажется логичным, т.к. нужно контролировать поток машин.

Идея Reload, отчасти, симуляция мультитура - возможность машины вернутся в какую-то локацию для погрузки-разгрузки. Я согласен, что тут тоже было бы неплохо ограничивать поток машин, но пока это не реализовано.

Вообще, эти две функциональности довольно-таки экспериментальные - могут быть нюансы при использовании с другими функциональными возможностями.

**Comment by yuranov** [comment]
Илья, благодарю за ответ!

Если честно, то я не очень понял про уникальность местоположения для Dispatch. Это ограничение из-за особенностей алгоритма? Т.е., по сути, это пример из реальной жизни, когда транспорт на ночь остается рядом со складом и начальное местоположение  для транспорта и для Dispatch будут одинаковые. 

И тогда еще есть предложение, если Dispatch рассматривать как склад, то тогда получается, что склад диктует условия свой работы, т.е. он нормирует время на обработки единицы транспорта, хотя, как мне кажется, склад должен иметь ограничения только по кол-ву одновременных загрузок, а вот длительность самой операции погрузки должна зависеть от типа транспорта. Фактически он должен как семафор в многопоточке.
Но если рассматривать его более комплексно, то тогда было бы здорово, если Dispatch был бы разделен на отдельные зоны погрузки/выгрузки с своими часами работы(соответсвенно, одна зона - одна машина одновременно, две зоны - две и так далее), это уже было бы ближе к реальным условиям, но в таком случае нужно учитывать еще время на выгрузку транспорта..

**Comment by reinterpretcat** [comment]
Я бы не сказал, что это ограничение алгоритма (хотя dispatch выбирается в самом начале, до вставки любой задачи). Скорее, логическое ограничение, исходя из тех предпосылок, что я выше описал. А так dispatch и ограничивает количество одновременных погрузок за определенный интервал, см. пример определения: 

https://github.com/reinterpretcat/vrp/blob/master/examples/data/pragmatic/basics/dispatch.basic.problem.json#L89-L114

Для разных зон, по идее, можно задать разные координаты. Т.к. dispatch часть определения типа машины, тут можно варьировать длительность всей операции для данного типа.

В целом, это экспереминтальная функциональность, я не много сталкивался с такими требованиями, поэтому могут быть нюансы самой модели dispatch.

**Comment by yuranov** [comment]
Все, я разорался с уникальным местоположением для dispatch. Мне выдавало ошибку E1306. Я думал, что все значения указаны верно и все сводится к тому, что я не могу указать одно и тоже место для начала маршрута транспорта и для dispatch, но оказалось, что проблема была не в этом.
Было бы здорово, если бы dispatch в будущем имел возможность работать как семафор, и не на группу, а не весь флот целиком =)
