### ISSUE TITLE
Invalid type error in console when trying the JS example

### ISSUE THREAD

**Issue by rahns** [reinterpretcat/vrp#37]
Hi,
I am attempting to use the pkg folder in the latest release of vrp_cli_wasm.zip with a index.html file containing the contents on the documentation page [here](https://reinterpretcat.github.io/vrp/examples/interop/javascript.html), however instead of the result being printed to the javascript console, I am presented with this error in the console:

![Screenshot 2021-08-08 142653](https://user-images.githubusercontent.com/33315529/128620774-dfd83f7c-a06a-4f88-b070-854a2a5b98bf.png)

I haven't modified any files in 'pkg' or the contents of 'index.html', and the routing locations are successfully printed to the console prior to the error message.

I am not sure if this is a bug or if I am doing something wrong, but I can't see why it shouldn't work as is.
Thanks in advance for any help.

**Comment by reinterpretcat** [comment]
Hi, thanks for reporting. Probably, it is related to recent format changes and outdated documentation. I'll check it

**Comment by reinterpretcat** [comment]
I corrected example in source code:

https://github.com/reinterpretcat/vrp/blob/master/docs/src/examples/interop/javascript.md

I'll update documentation with the next release (expecting soon)
