### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by ibatanov** [reinterpretcat/vrp#39]
Hi! I am very glad that there is a similar solution on rust, it is really very cool!
I recently started learning rust, and I wanted to create an example based on your solution in the following bundle actix-web -> vrp-pragmatic.
for example 
```  
    let environment = Arc::new(Environment::default());
    let core_problem = (request.problem.clone(), vec![request.matrix.clone()]).read_pragmatic();
    let core_problem = Arc::new(core_problem.unwrap_or_else(|errors| {
        panic!("cannot read pragmatic problem: {}", FormatError::format_many(errors.as_slice(), "\t\n"))
    }));
    let solver = Builder::new(core_problem.clone(), environment.clone())
        .with_max_time(Some(60))
        .with_max_generations(Some(100))
        .build()
        .unwrap();
    let (solution, _cost, _) = solver.solve().unwrap();
```

With this approach, I may have (not sure) detected a memory leak, because the memory is not released between load testing using the AB utility. I am using Instruments (mac os) to find the problem.
![Снимок экрана 2021-08-22 в 16 28 21](https://user-images.githubusercontent.com/40363077/130356994-c4745d19-7188-4f95-9aff-e23bc6eae4de.png)
As far as I understand, one of the problems is
https://github.com/reinterpretcat/vrp/blob/75dbb8f4e55461066cd7771654381f9195bc3cbb/vrp-core/src/solver/population/elitism.rs#L134

I will be grateful for any hint where to look next

**Comment by reinterpretcat** [comment]
Thanks for feedback!

To be honest, I don't see anything suspicious in sort function. Can it be related that there was a spike in usage, memory chunk was allocated, but not actually used by the app afterwards?

**Comment by ibatanov** [comment]
I also didn't see anything suspicious in this function, but when using testing as an example of ab -p test.json application/json -c 12 -n 1000 http://myurl the memory will constantly grow and not be released. According to observations, I was able to overclock the memory consumption to 1.5 GB and let the application "cool down", but the memory was not released. I will watch more.

I have already thought about the actix problems, but with simple examples, it does not consume more than 5mb of memory during ab stress testing

**Comment by reinterpretcat** [comment]
Localized a bit: it seems memory leak happens in rosomaxa population algorithm

**Comment by reinterpretcat** [comment]
I think I found it: it is in gsom network implementation

**Comment by reinterpretcat** [comment]
Fixed by https://github.com/reinterpretcat/vrp/commit/dd6179cce1e0bdab23bfd95dee4255c3d6728d09

**Comment by ibatanov** [comment]
Hi! Sorry, I didn't see any activity, I fell out for health reasons. Cool news, I will definitely test it in the near future!
