### ISSUE TITLE
Order of routing matrix

### ISSUE THREAD

**Issue by martsime** [reinterpretcat/vrp#4]
I've been trying to formulate our VRP using the pragmatic format as described in the docs, but ran into some issues with the routing matrix.

According to the docs, the routing matrix should be on the following format.

> |    |    |    |
> |----|----|----|
> |  0 | BA | CA |
> | AB |  0 | CB |
> | AC | BC |  0 |
> 
> 
> where
> - `0`: zero duration or distance
> - `XY`: distance or duration from X location to Y
> 
> As single dimensional array it looks like:
> 
>     [0,BA,CA,AB,0,CB,AC,BC,0]

Providing the matrix on that format does not give us correct distances when evaluating the solution. If we instead transpose the matrix everything seems to work fine.

|    |    |    |
|----|----|----|
|  0 | AB | AC |
| BA |  0 | BC |
| CA | CB |  0 |
     [0,AB,AC,BA,0,BC,CA,CB,0]

Are the docs outdated or do you know if we're doing something wrong?

**Comment by reinterpretcat** [comment]
Maybe there is a mistake in the documentation. I will double check, thanks!

**Comment by reinterpretcat** [comment]
I updated docs: https://reinterpretcat.github.io/vrp/concepts/pragmatic/routing/format.html
