### ISSUE TITLE
check input json: 'missing field `isConstrained` error received if document is followed

### ISSUE THREAD

**Issue by iedmrc** [reinterpretcat/vrp#49]
Hi,
According to the document:
```
tour-order: controls desired activity order in tours
is_constrained: violating order is not allowed, even if it leads to less assigned jobs (default is false).
```
`is_constrained` is snake case but throws the error:
```
check input json: 'missing field `isConstrained`
```
So it should be refactored as `isConstrained`

https://reinterpretcat.github.io/vrp/concepts/pragmatic/problem/objectives.html?highlight=tour-order#scalar-objectives

**Comment by reinterpretcat** [comment]
Thanks for reporting! It is typo in docs, fixed in https://github.com/reinterpretcat/vrp/commit/c722fce92e6e78441d530cf25673ea789a3bfd38
