### ISSUE TITLE
Using Java - getting geojson output

### ISSUE THREAD

**Issue by UserVrp** [reinterpretcat/vrp#5]
Hi ,

I'm trying to use the java example you published - i had a success with get_routing_locations and solve_pragmatic

In the answer i don't see the geojson output as i get it from vrp-cli command

how can i get the goejson also from the java code

Thanks in advance

**Comment by reinterpretcat** [comment]
Hi, this is not a part of exported API at the moment. To be honest, I'm not sure that it is really needed for programmatically accessible API as more advanced geojson can be created by the client themself.

**Comment by UserVrp** [comment]
Thank you for the answer -

Can you give me more direction how to create geojson by myself ?

Thanks in advance

**Comment by reinterpretcat** [comment]
Check the spec here: https://geojson.org/
Test your output: http://geojson.io
this is how it is done in the lib: https://github.com/reinterpretcat/vrp/blob/master/vrp-pragmatic/src/format/solution/geo_serializer.rs

**Comment by UserVrp** [comment]
Thanks a lot!!!
