### ISSUE TITLE
Add `vrp-web` and expose an endpoint for solving routes 

### ISSUE THREAD

**Issue by wesleimp** [reinterpretcat/vrp#52]
It would be awesome to use vrp solver as a web API.

**Comment by reinterpretcat** [comment]
I would say it is not in the scope of the project. If you're looking for some ideas regarding building such API, you can take a look at this repo: https://github.com/reinterpretcat/vrp-experiments . Here, I experimented with building VRP API (a bit outdated)

**Comment by wesleimp** [comment]
Nice. Makes sense. I’m gonna take a look at your experiments.
Thanks
