### ISSUE TITLE
the modern jemalloc for rust is at https://crates.io/crates/tikv-jemallocator

### ISSUE THREAD

**Issue by gustav3d** [reinterpretcat/vrp#59]
The original jemalloc your using is not maintaned, rustc and other projects switched to use a fork https://crates.io/crates/tikv-jemallocator

**Comment by reinterpretcat** [comment]
Thanks for sharing! I will recheck with this crate. At the moment, I'm relying on default allocator in master branch and in a `jemalloc` branch I'm just checking whether switching brings some obvious benefits.

**Comment by reinterpretcat** [comment]
Fixed in https://github.com/reinterpretcat/vrp/commit/5ff257bd1c5b6f39714e6e7383dae1d25ace2827
