### ISSUE TITLE
Failed with Distance Matrix

### ISSUE THREAD

**Issue by bgcopp** [reinterpretcat/vrp#6]
Hello, i'm testing this great solver ("congrats!"). I do multiples probes with fews jobs (10 and 20) that includes external distance matrix without problem. I'm a big test with 133 jobs and distance matrix to this number of jobs 133*133. But when run the solver i have a next  Error: "'**E1505, cause: 'amount of locations does not match matrix dimension', action: 'check matrix size: max location index ('127') should be less than matrix size ('133')'.**'". If run this problem without external distance matrix, run perfect and find a solution. I have checked the information several times to avoid formatting errors in the profile json. Can you help me? The number of jobs is 132 and the matrix is 133 x 133. how to send you this files ? Thank you for your response.

**Comment by reinterpretcat** [comment]
Hi, thanks for feedback!

It is invalid validation error message which I've just fixed in master branch. Regarding custom matrix, it must have expected size which corresponds to max index of location and it is determined automatically based on your problem definition.  

As described in [the docs](https://reinterpretcat.github.io/vrp/concepts/pragmatic/routing/index.html#location-format), you can specify location using geocoordinate or custom index. I guess you're using coordinates, not indices, and your problem definition has duplicated coordinates in different jobs or vehicles. That's why there is some mismatch.

 I suggest to use specific command to extract ordered list of locations and use it to prepare a matrix:

`vrp-cli solve pragmatic problem.json --get-locations -o locations.json`

if you want to keep matrix unchanged, then use location indices, but it can be easily error prone.

> how to send you this files ?

If there is no concern in privacy (e.g. GDPR), you can try to attach it to the ticket by drag and drop.

**Comment by bgcopp** [comment]
Thank you, the solver run ok. I have a trouble after some seconds the solver end process :+1: 
generation 4100 took 15ms,  rank: 0, cost: 8904.40(0.000%), tours: 28, unassigned: 47, fitness: (47.000, 28.000, 8904.400)
[67s] generation 4200 took 15ms,  rank: 0, cost: 8893.32(0.000%), tours: 28, unassigned: 47, fitness: (47.000, 28.000, 8893.316)
[68s] generation 4300 took 22ms,  rank: 0, cost: 8893.32(0.000%), tours: 28, unassigned: 47, fitness: (47.000, 28.000, 8893.316)
[70s] generation 4400 took 16ms,  rank: 0, cost: 8893.32(0.000%), tours: 28, unassigned: 47, fitness: (47.000, 28.000, 8893.316)
[72s] generation 4500 took 14ms,  rank: 0, cost: 8893.32(0.000%), tours: 28, unassigned: 47, fitness: (47.000, 28.000, 8893.316)
[73s] generation 4600 took 17ms,  rank: 0, cost: 8893.32(0.000%), tours: 28, unassigned: 47, fitness: (47.000, 28.000, 8893.316)
[75s] generation 4700 took 15ms,  rank: 0, cost: 8893.32(0.000%), tours: 28, unassigned: 47, fitness: (47.000, 28.000, 8893.316)
[76s] generation 4800 took 16ms,  rank: 0, cost: 8893.32(0.000%), tours: 28, unassigned: 47, fitness: (47.000, 28.000, 8893.316)
[78s] generation 4900 took 15ms,  rank: 0, cost: 8893.32(0.000%), tours: 28, unassigned: 47, fitness: (47.000, 28.000, 8893.316)
[80s] generation 5000 took 17ms,  rank: 0, cost: 8893.32(0.000%), tours: 28, unassigned: 47, fitness: (47.000, 28.000, 8893.316)
[80s] population state (speed: 62.39 gen/sec, improvement ratio: 0.011:0.002):
         rank: 0, cost: 8893.32(0.000%), tours: 28, unassigned: 47, fitness: (47.000, 28.000, 8893.316)
         rank: 0, cost: 8893.32(0.000%), tours: 28, unassigned: 47, fitness: (47.000, 28.000, 8893.316)
         rank: 0, cost: 8893.32(0.000%), tours: 28, unassigned: 47, fitness: (47.000, 28.000, 8893.316)
         rank: 1, cost: 8893.32(0.000%), tours: 28, unassigned: 47, fitness: (47.000, 28.000, 8893.316)
[80s] population state (speed: 62.41 gen/sec, improvement ratio: 0.011:0.002):
         rank: 0, cost: 8893.32(0.000%), tours: 28, unassigned: 47, fitness: (47.000, 28.000, 8893.316)
         rank: 0, cost: 8893.32(0.000%), tours: 28, unassigned: 47, fitness: (47.000, 28.000, 8893.316)
         rank: 0, cost: 8893.32(0.000%), tours: 28, unassigned: 47, fitness: (47.000, 28.000, 8893.316)
         rank: 1, cost: 8893.32(0.000%), tours: 28, unassigned: 47, fitness: (47.000, 28.000, 8893.316)
[80s] total generations: 5001, speed: 62.41 gen/sec

But the unassigned jobs = 47 and multiples vehicles not include in the solution. Why the solver not use all vehicles that need for problem. 

The fleet have 80 Vehicles and only use 28. If we use the vehicles not used, we can acomplish the job with timewindow.

Thak you for your help

unassigned jobs

"unassigned": [
    {
      "jobId": "job66 [TUNJA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job26 [ZIPAQUIRA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job34 [TIBASOSA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job56 [ZIPAQUIRA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job47 [TAURAMENA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job5 [LA CALERA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job89 [SOGAMOSO]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job80 [CAJICA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job51 [BOGOTA, D.C.]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job46 [SAMACA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job68 [TOCA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job23 [BARBOSA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job67 [DUITAMA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job90 [UBAQUE]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job38 [TUNJA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job13 [CAJICA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job41 [DUITAMA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job104 [SIMIJACA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job11 [BOGOTA, D.C.]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job74 [CAJICA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job60 [BOGOTA, D.C.]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job31 [TUNJA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job63 [RAMIRIQUI]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job119 [TUNJA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job82 [RAQUIRA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job98 [TABIO]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job108 [BOGOTA, D.C.]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job6 [GACHANCIPA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job109 [TUNJA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job86 [CHIA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job97 [BOGOTA, D.C.]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job118 [BOGOTA, D.C.]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job4 [TOCANCIPA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job55 [SOPO]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job129 [CAJICA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job95 [CAJICA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job17 [BOGOTA, D.C.]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job24 [AQUITANIA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job130 [BOGOTA, D.C.]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job28 [BOGOTA, D.C.]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job54 [ZIPAQUIRA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job123 [BOGOTA, D.C.]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job124 [TUNJA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job65 [SOGAMOSO]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job132 [SANTANA]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    },
    {
      "jobId": "job102 [NEMOCON]",
      "reasons": [
        {
          "code": 2,
          "description": "cannot be visited within time window"
        }
      ]
    }

**Comment by reinterpretcat** [comment]
It is hard to say what is exact problem without seeing your problem definition and routing matrix. As the reason of unassignment is time window, my guess is that these jobs are far away from depot location.

**Comment by bgcopp** [comment]
Thak you for your response. This is the link for download files. https://www.dropbox.com/sh/5o5kwkicuyi8p08/AACrya1e3JmQ7QJmdaIt1RAva?dl=0

Thank you for your help.

**Comment by reinterpretcat** [comment]
Hi! I've checked your data and it seems to be a valid solution: you have quite big durations between some locations in the routing matrix,, e.g. like 220154 which is ~61 hours when your shift times are less than 24 hours and single depot:

![image](https://user-images.githubusercontent.com/1611077/92961384-703fd480-f46f-11ea-997c-d35d7671e4ad.png)
(just run the solver for short time, unassigned jobs are not shown, need to add them into geojson output)

**Comment by bgcopp** [comment]
Thaks for your response.  I have checked the information several times. the value "220154" (220 km) is into distances array not for travelTimes. in fact the max travel time is (6.6h) "23795".  I did other test without profile and distance matrix.
 
     vrp-cli solve pragmatic problem.json -o solution.json -g solution.geojson --log

the result is 

[42s] population state (speed: 70.81 gen/sec, improvement ratio: 0.033:0.021):
         rank: 0, cost: 11020.32(0.000%), tours: 26, unassigned: 39, fitness: (39.000, 26.000, 11020.323)
         rank: 0, cost: 11020.32(0.000%), tours: 26, unassigned: 39, fitness: (39.000, 26.000, 11020.323)
         rank: 0, cost: 11020.32(0.000%), tours: 26, unassigned: 39, fitness: (39.000, 26.000, 11020.323)
         rank: 1, cost: 11024.05(0.034%), tours: 26, unassigned: 39, fitness: (39.000, 26.000, 11024.048)
[42s] total generations: 3001, speed: 70.81 gen/sec

With multiples vehicles unused i have unassigned jobs: 39. The behavior is right? or what am I doing wrong?

Thakyou

**Comment by reinterpretcat** [comment]
Yes, you're right, it is distance.

I did the following trick: removed shift end and reload (it is experimental feature) and run the problem again. Results are 
60 tours, 0 unassigned jobs and 3 unassigned breaks (counted as unassigned in the logs). So, end shift seems to be one of the reasons.

Second reason is default objective function: minimize amount of tours and assigned jobs first, second - cost. So, if amount of unassigned is dropped, but tours - increased, solution might be not top ranked. I guess this is your objective:
```

  "objectives": {
    "primary": [
      {
        "type": "minimize-unassigned"
      }
    ],
    "secondary": [
      {
        "type": "minimize-cost"
      }
    ]
  }
```

More info about objectives [here](https://reinterpretcat.github.io/vrp/concepts/pragmatic/problem/objectives.html)

I run with this objective and got 44 unassigned and 34 tours. Still not zero unassigned. Based on the first finding, seems there is no enough time to return to depot after serving these jobs: if I give another extra 4 hrs, then getting more tours (53 and less unassigned (17).
