### ISSUE TITLE
New objective "earliest-end-date"

### ISSUE THREAD

**Issue by nkl1996** [reinterpretcat/vrp#69]
Hey, i want to optimize a job with multiple shifts over a month, teams and tours. When i solve this problem i get a solution thats spreads the tour dates randomly over this time period even so the problem can be done in half the time period. I want the tours to be as early as possible, so the teams are free for the rest of the time.

Is there a possibility to archive this or can you program a new objective for this?

**Comment by reinterpretcat** [comment]
Yes, it can happen and I think it can be solved by adding a custom objective function which will try to minimize a sum of tour arrival times. At the moment, it is not there in pragmatic format

**Comment by nkl1996** [comment]
Can you add such objective function in the near feature or is it not planned? I never programmed anything in rust otherwise i would give it a try.

**Comment by reinterpretcat** [comment]
I can implement such global objective a bit later after my current task, but it might be not enough for some problems as the simple implementation will guide the search on solution comparison level. This won't be enough for large problems as it might require more time to redistribute jobs. Alternative solution could be pre-processing on client side and splitting problems into multiple according to shift times (of course, can be done internally too with more sophisticated implementation).

**Comment by reinterpretcat** [comment]
Some functionality is added here: https://github.com/reinterpretcat/vrp/commit/31ac6ad6bcae5afe7069600855d09e928fa13eb5
