### ISSUE TITLE
"Idling time" to start a tour

### ISSUE THREAD

**Issue by jotel96** [reinterpretcat/vrp#71]
Hey,
I've found an issue that seems to appear randomly when trying to solve a problem. Sometimes the tour states to wait some amount of time before departure. I can't really figure out why tho.
This times also varies from try to try, sometimes the departure works as expected (06:00) and sometimes it wait for a minute or an hour.
Is this a known problem and do you know any fix for that?
Thanks in advance.

[routing_matrix.txt](https://github.com/reinterpretcat/vrp/files/8034106/routing_matrix.txt)
[solution.txt](https://github.com/reinterpretcat/vrp/files/8034107/solution.txt)
[problem.txt](https://github.com/reinterpretcat/vrp/files/8034108/problem.txt)
.

**Comment by reinterpretcat** [comment]
Hi, I think it is related to departure time optimization which is used by default if you don't specify `latest` property on shift's start the same as `earliest`. It is useful to avoid some waiting time at the first activity (and others) when the problem has time windows on jobs. I guess you can simply specify `latest` = `earliest` on the shift to have stable departure time

**Comment by jotel96** [comment]
Thank you, that fixed my issue.
