### ISSUE TITLE
Regression - telemetry metrics are not included in the solution file in v1.17.0

### ISSUE THREAD

**Issue by tdeenes** [reinterpretcat/vrp#77]
Hi @reinterpretcat , I tested the new release and found that even though I ask for telemetry metrics in the config file, it is not included in the solution. E.g.:
```
{
  "termination": {
    "maxTime": 600,
    "maxGenerations": 1000
  },
  "environment": {
    "parallelism": {
      "numThreadPools": 1,
      "threadsPerPool": 2
    },
    "logging": {
      "enabled": true,
      "prefix": "testing"
    }
  },
  "telemetry": {
    "progress": {
      "enabled": true,
      "logBest": 100,
      "logPopulation": 1000,
      "dumpPopulation": false
    },
    "metrics": {
      "enabled": true,
      "trackPopulation": 500
    }
  }
}
```

**Comment by tdeenes** [comment]
I checked out this commit (1ca3d70ae831280c87657255e17b8aa8bd28a2bc) which I suppose is the last commit before you refactored the telemetry interface and I can confirm it worked as expected.

**Comment by reinterpretcat** [comment]
This commit should fix it: https://github.com/reinterpretcat/vrp/commit/2985bf51fd22c533372f4cacc00595c35dbbaeef

**Comment by tdeenes** [comment]
Indeed, it works now. Thank you for the quick fix!
